package com.dieson.green.pojo;

public class AlembicVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alembic_version.version_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String versionNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alembic_version.version_num
     *
     * @return the value of alembic_version.version_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getVersionNum() {
        return versionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alembic_version.version_num
     *
     * @param versionNum the value for alembic_version.version_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setVersionNum(String versionNum) {
        this.versionNum = versionNum == null ? null : versionNum.trim();
    }
}