package com.dieson.green.pojo;

public class AuthUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.auth_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.user_id
     *
     * @return the value of auth_user.user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.user_id
     *
     * @param userId the value for auth_user.user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.auth_id
     *
     * @return the value of auth_user.auth_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.auth_id
     *
     * @param authId the value for auth_user.auth_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }
}