package com.dieson.green.pojo;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.id
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.rose
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    private Integer rose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.project
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    private Integer project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.user_id
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.id
     *
     * @return the value of author.id
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.id
     *
     * @param id the value for author.id
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.rose
     *
     * @return the value of author.rose
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public Integer getRose() {
        return rose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.rose
     *
     * @param rose the value for author.rose
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public void setRose(Integer rose) {
        this.rose = rose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.project
     *
     * @return the value of author.project
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public Integer getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.project
     *
     * @param project the value for author.project
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public void setProject(Integer project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.user_id
     *
     * @return the value of author.user_id
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.user_id
     *
     * @param userId the value for author.user_id
     *
     * @mbg.generated Tue Jul 24 13:39:41 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}