package com.dieson.green.pojo;

public class Depend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depend.case_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depend.suite_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer suiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depend.attred
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String attred;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depend.case_id
     *
     * @return the value of depend.case_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depend.case_id
     *
     * @param caseId the value for depend.case_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depend.suite_id
     *
     * @return the value of depend.suite_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getSuiteId() {
        return suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depend.suite_id
     *
     * @param suiteId the value for depend.suite_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setSuiteId(Integer suiteId) {
        this.suiteId = suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depend.attred
     *
     * @return the value of depend.attred
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getAttred() {
        return attred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depend.attred
     *
     * @param attred the value for depend.attred
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setAttred(String attred) {
        this.attred = attred == null ? null : attred.trim();
    }
}