package com.dieson.green.pojo;

public class EmialReports {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.id
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.email_re_user_id
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private Integer emailReUserId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.send_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private String sendEmail;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.send_email_password
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private String sendEmailPassword;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.to_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private String toEmail;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.default_set
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private Boolean defaultSet;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.port
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private Integer port;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.stmp_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private String stmpEmail;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column email_reports.status
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	private Boolean status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.id
	 *
	 * @return the value of email_reports.id
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.id
	 *
	 * @param id
	 *            the value for email_reports.id
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.email_re_user_id
	 *
	 * @return the value of email_reports.email_re_user_id
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public Integer getEmailReUserId() {
		return emailReUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.email_re_user_id
	 *
	 * @param emailReUserId
	 *            the value for email_reports.email_re_user_id
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setEmailReUserId(Integer emailReUserId) {
		this.emailReUserId = emailReUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.send_email
	 *
	 * @return the value of email_reports.send_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public String getSendEmail() {
		return sendEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.send_email
	 *
	 * @param sendEmail
	 *            the value for email_reports.send_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setSendEmail(String sendEmail) {
		this.sendEmail = sendEmail == null ? null : sendEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.send_email_password
	 *
	 * @return the value of email_reports.send_email_password
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public String getSendEmailPassword() {
		return sendEmailPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.send_email_password
	 *
	 * @param sendEmailPassword
	 *            the value for email_reports.send_email_password
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setSendEmailPassword(String sendEmailPassword) {
		this.sendEmailPassword = sendEmailPassword == null ? null : sendEmailPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.to_email
	 *
	 * @return the value of email_reports.to_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public String getToEmail() {
		return toEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.to_email
	 *
	 * @param toEmail
	 *            the value for email_reports.to_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setToEmail(String toEmail) {
		this.toEmail = toEmail == null ? null : toEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.default_set
	 *
	 * @return the value of email_reports.default_set
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public Boolean getDefaultSet() {
		return defaultSet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.default_set
	 *
	 * @param defaultSet
	 *            the value for email_reports.default_set
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setDefaultSet(Boolean defaultSet) {
		this.defaultSet = defaultSet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.port
	 *
	 * @return the value of email_reports.port
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.port
	 *
	 * @param port
	 *            the value for email_reports.port
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.stmp_email
	 *
	 * @return the value of email_reports.stmp_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public String getStmpEmail() {
		return stmpEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.stmp_email
	 *
	 * @param stmpEmail
	 *            the value for email_reports.stmp_email
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setStmpEmail(String stmpEmail) {
		this.stmpEmail = stmpEmail == null ? null : stmpEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column email_reports.status
	 *
	 * @return the value of email_reports.status
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column email_reports.status
	 *
	 * @param status
	 *            the value for email_reports.status
	 *
	 * @mbg.generated Mon Jul 09 15:06:28 CST 2018
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}
}