package com.dieson.green.pojo;

public class Interfaces {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.model_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer projectsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.Interface_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.Interface_url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.Interface_meth
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceMeth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.Interface_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceHeaders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaces.interface_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.id
     *
     * @return the value of interfaces.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.id
     *
     * @param id the value for interfaces.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.model_id
     *
     * @return the value of interfaces.model_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.model_id
     *
     * @param modelId the value for interfaces.model_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.projects_id
     *
     * @return the value of interfaces.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getProjectsId() {
        return projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.projects_id
     *
     * @param projectsId the value for interfaces.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setProjectsId(Integer projectsId) {
        this.projectsId = projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.Interface_name
     *
     * @return the value of interfaces.Interface_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.Interface_name
     *
     * @param interfaceName the value for interfaces.Interface_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.Interface_url
     *
     * @return the value of interfaces.Interface_url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceUrl() {
        return interfaceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.Interface_url
     *
     * @param interfaceUrl the value for interfaces.Interface_url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceUrl(String interfaceUrl) {
        this.interfaceUrl = interfaceUrl == null ? null : interfaceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.Interface_meth
     *
     * @return the value of interfaces.Interface_meth
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceMeth() {
        return interfaceMeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.Interface_meth
     *
     * @param interfaceMeth the value for interfaces.Interface_meth
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceMeth(String interfaceMeth) {
        this.interfaceMeth = interfaceMeth == null ? null : interfaceMeth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.status
     *
     * @return the value of interfaces.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.status
     *
     * @param status the value for interfaces.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.Interface_headers
     *
     * @return the value of interfaces.Interface_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceHeaders() {
        return interfaceHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.Interface_headers
     *
     * @param interfaceHeaders the value for interfaces.Interface_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceHeaders(String interfaceHeaders) {
        this.interfaceHeaders = interfaceHeaders == null ? null : interfaceHeaders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaces.interface_type
     *
     * @return the value of interfaces.interface_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaces.interface_type
     *
     * @param interfaceType the value for interfaces.interface_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType == null ? null : interfaceType.trim();
    }
}