package com.dieson.green.pojo;

import java.util.Date;

public class MockServer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.make_uers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer makeUers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.path
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.methods
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String methods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String headers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.description
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.return_para
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String returnPara;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.params
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.rebacktype
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String rebacktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.update_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.delete
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.is_check
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean isCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_server.is_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean isHeaders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.id
     *
     * @return the value of mock_server.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.id
     *
     * @param id the value for mock_server.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.make_uers
     *
     * @return the value of mock_server.make_uers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getMakeUers() {
        return makeUers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.make_uers
     *
     * @param makeUers the value for mock_server.make_uers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setMakeUers(Integer makeUers) {
        this.makeUers = makeUers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.name
     *
     * @return the value of mock_server.name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.name
     *
     * @param name the value for mock_server.name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.path
     *
     * @return the value of mock_server.path
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.path
     *
     * @param path the value for mock_server.path
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.methods
     *
     * @return the value of mock_server.methods
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getMethods() {
        return methods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.methods
     *
     * @param methods the value for mock_server.methods
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setMethods(String methods) {
        this.methods = methods == null ? null : methods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.headers
     *
     * @return the value of mock_server.headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getHeaders() {
        return headers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.headers
     *
     * @param headers the value for mock_server.headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setHeaders(String headers) {
        this.headers = headers == null ? null : headers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.description
     *
     * @return the value of mock_server.description
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.description
     *
     * @param description the value for mock_server.description
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.return_para
     *
     * @return the value of mock_server.return_para
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getReturnPara() {
        return returnPara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.return_para
     *
     * @param returnPara the value for mock_server.return_para
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setReturnPara(String returnPara) {
        this.returnPara = returnPara == null ? null : returnPara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.params
     *
     * @return the value of mock_server.params
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.params
     *
     * @param params the value for mock_server.params
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.rebacktype
     *
     * @return the value of mock_server.rebacktype
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getRebacktype() {
        return rebacktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.rebacktype
     *
     * @param rebacktype the value for mock_server.rebacktype
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setRebacktype(String rebacktype) {
        this.rebacktype = rebacktype == null ? null : rebacktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.update_time
     *
     * @return the value of mock_server.update_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.update_time
     *
     * @param updateTime the value for mock_server.update_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.status
     *
     * @return the value of mock_server.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.status
     *
     * @param status the value for mock_server.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.delete
     *
     * @return the value of mock_server.delete
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.delete
     *
     * @param delete the value for mock_server.delete
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.is_check
     *
     * @return the value of mock_server.is_check
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.is_check
     *
     * @param isCheck the value for mock_server.is_check
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setIsCheck(Boolean isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_server.is_headers
     *
     * @return the value of mock_server.is_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getIsHeaders() {
        return isHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_server.is_headers
     *
     * @param isHeaders the value for mock_server.is_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setIsHeaders(Boolean isHeaders) {
        this.isHeaders = isHeaders;
    }
}