package com.dieson.green.pojo;

public class Parames {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.interface_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer interfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.parameter_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String parameterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.parameter_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String parameterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.necessary
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean necessary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.demo
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String demo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.id
     *
     * @return the value of parames.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.id
     *
     * @param id the value for parames.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.interface_id
     *
     * @return the value of parames.interface_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.interface_id
     *
     * @param interfaceId the value for parames.interface_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.parameter_type
     *
     * @return the value of parames.parameter_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getParameterType() {
        return parameterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.parameter_type
     *
     * @param parameterType the value for parames.parameter_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setParameterType(String parameterType) {
        this.parameterType = parameterType == null ? null : parameterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.parameter_name
     *
     * @return the value of parames.parameter_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.parameter_name
     *
     * @param parameterName the value for parames.parameter_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName == null ? null : parameterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.necessary
     *
     * @return the value of parames.necessary
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getNecessary() {
        return necessary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.necessary
     *
     * @param necessary the value for parames.necessary
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setNecessary(Boolean necessary) {
        this.necessary = necessary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.type
     *
     * @return the value of parames.type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.type
     *
     * @param type the value for parames.type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.status
     *
     * @return the value of parames.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.status
     *
     * @param status the value for parames.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.demo
     *
     * @return the value of parames.demo
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDemo() {
        return demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.demo
     *
     * @param demo the value for parames.demo
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDemo(String demo) {
        this.demo = demo == null ? null : demo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.desc
     *
     * @return the value of parames.desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.desc
     *
     * @param desc the value for parames.desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.user_id
     *
     * @return the value of parames.user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.user_id
     *
     * @param userId the value for parames.user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}