package com.dieson.green.pojo;

public class Projects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.project_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer projectUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.project_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.id
     *
     * @return the value of projects.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.id
     *
     * @param id the value for projects.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.project_user_id
     *
     * @return the value of projects.project_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getProjectUserId() {
        return projectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.project_user_id
     *
     * @param projectUserId the value for projects.project_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setProjectUserId(Integer projectUserId) {
        this.projectUserId = projectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.project_name
     *
     * @return the value of projects.project_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.project_name
     *
     * @param projectName the value for projects.project_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.status
     *
     * @return the value of projects.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.status
     *
     * @param status the value for projects.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}