package com.dieson.green.pojo;

public class Registrations {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrations.task_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrations.test_interface_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer testInterfaceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrations.task_id
     *
     * @return the value of registrations.task_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrations.task_id
     *
     * @param taskId the value for registrations.task_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrations.test_interface_id
     *
     * @return the value of registrations.test_interface_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getTestInterfaceId() {
        return testInterfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrations.test_interface_id
     *
     * @param testInterfaceId the value for registrations.test_interface_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTestInterfaceId(Integer testInterfaceId) {
        this.testInterfaceId = testInterfaceId;
    }
}