package com.dieson.green.pojo;

import java.util.Date;

public class Tasks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.make_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer makeUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String taskDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_start
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String taskStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_make_date
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Date taskMakeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_repor_to
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String taskReporTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_repor_operate
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String taskReporOperate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_make_email
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String taskMakeEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.run_status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String runStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.prject
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer prject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.test_event
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer testEvent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.id
     *
     * @return the value of tasks.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.id
     *
     * @param id the value for tasks.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.make_user
     *
     * @return the value of tasks.make_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getMakeUser() {
        return makeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.make_user
     *
     * @param makeUser the value for tasks.make_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setMakeUser(Integer makeUser) {
        this.makeUser = makeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_name
     *
     * @return the value of tasks.task_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_name
     *
     * @param taskName the value for tasks.task_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_desc
     *
     * @return the value of tasks.task_desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_desc
     *
     * @param taskDesc the value for tasks.task_desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc == null ? null : taskDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_start
     *
     * @return the value of tasks.task_start
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTaskStart() {
        return taskStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_start
     *
     * @param taskStart the value for tasks.task_start
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskStart(String taskStart) {
        this.taskStart = taskStart == null ? null : taskStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_make_date
     *
     * @return the value of tasks.task_make_date
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Date getTaskMakeDate() {
        return taskMakeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_make_date
     *
     * @param taskMakeDate the value for tasks.task_make_date
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskMakeDate(Date taskMakeDate) {
        this.taskMakeDate = taskMakeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_repor_to
     *
     * @return the value of tasks.task_repor_to
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTaskReporTo() {
        return taskReporTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_repor_to
     *
     * @param taskReporTo the value for tasks.task_repor_to
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskReporTo(String taskReporTo) {
        this.taskReporTo = taskReporTo == null ? null : taskReporTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_repor_operate
     *
     * @return the value of tasks.task_repor_operate
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTaskReporOperate() {
        return taskReporOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_repor_operate
     *
     * @param taskReporOperate the value for tasks.task_repor_operate
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskReporOperate(String taskReporOperate) {
        this.taskReporOperate = taskReporOperate == null ? null : taskReporOperate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_make_email
     *
     * @return the value of tasks.task_make_email
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTaskMakeEmail() {
        return taskMakeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_make_email
     *
     * @param taskMakeEmail the value for tasks.task_make_email
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTaskMakeEmail(String taskMakeEmail) {
        this.taskMakeEmail = taskMakeEmail == null ? null : taskMakeEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.status
     *
     * @return the value of tasks.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.status
     *
     * @param status the value for tasks.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.run_status
     *
     * @return the value of tasks.run_status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.run_status
     *
     * @param runStatus the value for tasks.run_status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setRunStatus(String runStatus) {
        this.runStatus = runStatus == null ? null : runStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.prject
     *
     * @return the value of tasks.prject
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getPrject() {
        return prject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.prject
     *
     * @param prject the value for tasks.prject
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setPrject(Integer prject) {
        this.prject = prject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.test_event
     *
     * @return the value of tasks.test_event
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getTestEvent() {
        return testEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.test_event
     *
     * @param testEvent the value for tasks.test_event
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTestEvent(Integer testEvent) {
        this.testEvent = testEvent;
    }
}