package com.dieson.green.pojo;

public class TestEnvironment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.make_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer makeUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.project
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String database;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.database_password
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String databasePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.database_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String databaseUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.db_host
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String dbHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_environment.db_port
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String dbPort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.id
     *
     * @return the value of test_environment.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.id
     *
     * @param id the value for test_environment.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.make_user
     *
     * @return the value of test_environment.make_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getMakeUser() {
        return makeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.make_user
     *
     * @param makeUser the value for test_environment.make_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setMakeUser(Integer makeUser) {
        this.makeUser = makeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.url
     *
     * @return the value of test_environment.url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.url
     *
     * @param url the value for test_environment.url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.project
     *
     * @return the value of test_environment.project
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.project
     *
     * @param project the value for test_environment.project
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setProject(Integer project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.status
     *
     * @return the value of test_environment.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.status
     *
     * @param status the value for test_environment.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.desc
     *
     * @return the value of test_environment.desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.desc
     *
     * @param desc the value for test_environment.desc
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.database
     *
     * @return the value of test_environment.database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDatabase() {
        return database;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.database
     *
     * @param database the value for test_environment.database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDatabase(String database) {
        this.database = database == null ? null : database.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.database_password
     *
     * @return the value of test_environment.database_password
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDatabasePassword() {
        return databasePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.database_password
     *
     * @param databasePassword the value for test_environment.database_password
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDatabasePassword(String databasePassword) {
        this.databasePassword = databasePassword == null ? null : databasePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.database_user
     *
     * @return the value of test_environment.database_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDatabaseUser() {
        return databaseUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.database_user
     *
     * @param databaseUser the value for test_environment.database_user
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDatabaseUser(String databaseUser) {
        this.databaseUser = databaseUser == null ? null : databaseUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.db_host
     *
     * @return the value of test_environment.db_host
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDbHost() {
        return dbHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.db_host
     *
     * @param dbHost the value for test_environment.db_host
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDbHost(String dbHost) {
        this.dbHost = dbHost == null ? null : dbHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_environment.db_port
     *
     * @return the value of test_environment.db_port
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDbPort() {
        return dbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_environment.db_port
     *
     * @param dbPort the value for test_environment.db_port
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDbPort(String dbPort) {
        this.dbPort = dbPort == null ? null : dbPort.trim();
    }
}