package com.dieson.green.pojo;

import java.util.Date;

public class TestResults {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.test_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer testUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.test_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer testNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.pass_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer passNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.fail_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer failNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.test_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Date testTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.hour_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer hourTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.test_log
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String testLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.test_rep
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String testRep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer projectsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.exception_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer exceptionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.para_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer paraNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_results.unknow_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer unknowNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.id
     *
     * @return the value of test_results.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.id
     *
     * @param id the value for test_results.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.test_user_id
     *
     * @return the value of test_results.test_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getTestUserId() {
        return testUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.test_user_id
     *
     * @param testUserId the value for test_results.test_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTestUserId(Integer testUserId) {
        this.testUserId = testUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.test_num
     *
     * @return the value of test_results.test_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getTestNum() {
        return testNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.test_num
     *
     * @param testNum the value for test_results.test_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTestNum(Integer testNum) {
        this.testNum = testNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.pass_num
     *
     * @return the value of test_results.pass_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getPassNum() {
        return passNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.pass_num
     *
     * @param passNum the value for test_results.pass_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setPassNum(Integer passNum) {
        this.passNum = passNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.fail_num
     *
     * @return the value of test_results.fail_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.fail_num
     *
     * @param failNum the value for test_results.fail_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setFailNum(Integer failNum) {
        this.failNum = failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.test_time
     *
     * @return the value of test_results.test_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.test_time
     *
     * @param testTime the value for test_results.test_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.hour_time
     *
     * @return the value of test_results.hour_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getHourTime() {
        return hourTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.hour_time
     *
     * @param hourTime the value for test_results.hour_time
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setHourTime(Integer hourTime) {
        this.hourTime = hourTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.test_log
     *
     * @return the value of test_results.test_log
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTestLog() {
        return testLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.test_log
     *
     * @param testLog the value for test_results.test_log
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTestLog(String testLog) {
        this.testLog = testLog == null ? null : testLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.test_rep
     *
     * @return the value of test_results.test_rep
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getTestRep() {
        return testRep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.test_rep
     *
     * @param testRep the value for test_results.test_rep
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setTestRep(String testRep) {
        this.testRep = testRep == null ? null : testRep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.projects_id
     *
     * @return the value of test_results.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getProjectsId() {
        return projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.projects_id
     *
     * @param projectsId the value for test_results.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setProjectsId(Integer projectsId) {
        this.projectsId = projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.status
     *
     * @return the value of test_results.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.status
     *
     * @param status the value for test_results.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.exception_num
     *
     * @return the value of test_results.exception_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getExceptionNum() {
        return exceptionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.exception_num
     *
     * @param exceptionNum the value for test_results.exception_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setExceptionNum(Integer exceptionNum) {
        this.exceptionNum = exceptionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.para_num
     *
     * @return the value of test_results.para_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getParaNum() {
        return paraNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.para_num
     *
     * @param paraNum the value for test_results.para_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setParaNum(Integer paraNum) {
        this.paraNum = paraNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_results.unknow_num
     *
     * @return the value of test_results.unknow_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getUnknowNum() {
        return unknowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_results.unknow_num
     *
     * @param unknowNum the value for test_results.unknow_num
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setUnknowNum(Integer unknowNum) {
        this.unknowNum = unknowNum;
    }
}