package com.dieson.green.pojo;

import java.util.Date;

public class TestCaseResults {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case_results.id
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case_results.case_id
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    private Integer caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case_results.result
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case_results.date
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case_results.test_evm
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    private Integer testEvm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_results.id
     *
     * @return the value of test_case_results.id
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_results.id
     *
     * @param id the value for test_case_results.id
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_results.case_id
     *
     * @return the value of test_case_results.case_id
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_results.case_id
     *
     * @param caseId the value for test_case_results.case_id
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_results.result
     *
     * @return the value of test_case_results.result
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_results.result
     *
     * @param result the value for test_case_results.result
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_results.date
     *
     * @return the value of test_case_results.date
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_results.date
     *
     * @param date the value for test_case_results.date
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_results.test_evm
     *
     * @return the value of test_case_results.test_evm
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public Integer getTestEvm() {
        return testEvm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_results.test_evm
     *
     * @param testEvm the value for test_case_results.test_evm
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    public void setTestEvm(Integer testEvm) {
        this.testEvm = testEvm;
    }
}