package com.dieson.green.pojo;

public class TestCase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.id
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.interface_id
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private Integer interfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.request_type
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private String requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.request_header
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private String requestHeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.request_para
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private String requestPara;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.request_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private String requestData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.status_code
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private Integer statusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.response_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private String responseData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.expect_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private String expectData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.save_result
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private Boolean saveResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.check_point
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    private String checkPoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.id
     *
     * @return the value of test_case.id
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.id
     *
     * @param id the value for test_case.id
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.interface_id
     *
     * @return the value of test_case.interface_id
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.interface_id
     *
     * @param interfaceId the value for test_case.interface_id
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.request_type
     *
     * @return the value of test_case.request_type
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.request_type
     *
     * @param requestType the value for test_case.request_type
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.request_header
     *
     * @return the value of test_case.request_header
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public String getRequestHeader() {
        return requestHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.request_header
     *
     * @param requestHeader the value for test_case.request_header
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setRequestHeader(String requestHeader) {
        this.requestHeader = requestHeader == null ? null : requestHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.request_para
     *
     * @return the value of test_case.request_para
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public String getRequestPara() {
        return requestPara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.request_para
     *
     * @param requestPara the value for test_case.request_para
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setRequestPara(String requestPara) {
        this.requestPara = requestPara == null ? null : requestPara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.request_data
     *
     * @return the value of test_case.request_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public String getRequestData() {
        return requestData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.request_data
     *
     * @param requestData the value for test_case.request_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setRequestData(String requestData) {
        this.requestData = requestData == null ? null : requestData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.status_code
     *
     * @return the value of test_case.status_code
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.status_code
     *
     * @param statusCode the value for test_case.status_code
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.response_data
     *
     * @return the value of test_case.response_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public String getResponseData() {
        return responseData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.response_data
     *
     * @param responseData the value for test_case.response_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setResponseData(String responseData) {
        this.responseData = responseData == null ? null : responseData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.expect_data
     *
     * @return the value of test_case.expect_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public String getExpectData() {
        return expectData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.expect_data
     *
     * @param expectData the value for test_case.expect_data
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setExpectData(String expectData) {
        this.expectData = expectData == null ? null : expectData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.save_result
     *
     * @return the value of test_case.save_result
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public Boolean getSaveResult() {
        return saveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.save_result
     *
     * @param saveResult the value for test_case.save_result
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setSaveResult(Boolean saveResult) {
        this.saveResult = saveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.check_point
     *
     * @return the value of test_case.check_point
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public String getCheckPoint() {
        return checkPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.check_point
     *
     * @param checkPoint the value for test_case.check_point
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    public void setCheckPoint(String checkPoint) {
        this.checkPoint = checkPoint == null ? null : checkPoint.trim();
    }
}