package com.dieson.green.pojo;

public class TestInterface {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.model_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer projectsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_meth
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceMeth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_pase
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfacePase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_assert
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceAssert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer interfaceUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceHeaders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_is_debug
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean interfaceIsDebug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.Interface_debug_whether
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean interfaceDebugWhether;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.getattr_p
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String getattrP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.pid
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.save_result
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean saveResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.select_database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String selectDatabase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.database_field
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String databaseField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.is_database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Boolean isDatabase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_interface.interface_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String interfaceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.id
     *
     * @return the value of test_interface.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.id
     *
     * @param id the value for test_interface.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.model_id
     *
     * @return the value of test_interface.model_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.model_id
     *
     * @param modelId the value for test_interface.model_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.projects_id
     *
     * @return the value of test_interface.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getProjectsId() {
        return projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.projects_id
     *
     * @param projectsId the value for test_interface.projects_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setProjectsId(Integer projectsId) {
        this.projectsId = projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_name
     *
     * @return the value of test_interface.Interface_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_name
     *
     * @param interfaceName the value for test_interface.Interface_name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_url
     *
     * @return the value of test_interface.Interface_url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceUrl() {
        return interfaceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_url
     *
     * @param interfaceUrl the value for test_interface.Interface_url
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceUrl(String interfaceUrl) {
        this.interfaceUrl = interfaceUrl == null ? null : interfaceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_meth
     *
     * @return the value of test_interface.Interface_meth
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceMeth() {
        return interfaceMeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_meth
     *
     * @param interfaceMeth the value for test_interface.Interface_meth
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceMeth(String interfaceMeth) {
        this.interfaceMeth = interfaceMeth == null ? null : interfaceMeth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_pase
     *
     * @return the value of test_interface.Interface_pase
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfacePase() {
        return interfacePase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_pase
     *
     * @param interfacePase the value for test_interface.Interface_pase
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfacePase(String interfacePase) {
        this.interfacePase = interfacePase == null ? null : interfacePase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_assert
     *
     * @return the value of test_interface.Interface_assert
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceAssert() {
        return interfaceAssert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_assert
     *
     * @param interfaceAssert the value for test_interface.Interface_assert
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceAssert(String interfaceAssert) {
        this.interfaceAssert = interfaceAssert == null ? null : interfaceAssert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_user_id
     *
     * @return the value of test_interface.Interface_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getInterfaceUserId() {
        return interfaceUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_user_id
     *
     * @param interfaceUserId the value for test_interface.Interface_user_id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceUserId(Integer interfaceUserId) {
        this.interfaceUserId = interfaceUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.status
     *
     * @return the value of test_interface.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.status
     *
     * @param status the value for test_interface.status
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_headers
     *
     * @return the value of test_interface.Interface_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceHeaders() {
        return interfaceHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_headers
     *
     * @param interfaceHeaders the value for test_interface.Interface_headers
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceHeaders(String interfaceHeaders) {
        this.interfaceHeaders = interfaceHeaders == null ? null : interfaceHeaders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_is_debug
     *
     * @return the value of test_interface.Interface_is_debug
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getInterfaceIsDebug() {
        return interfaceIsDebug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_is_debug
     *
     * @param interfaceIsDebug the value for test_interface.Interface_is_debug
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceIsDebug(Boolean interfaceIsDebug) {
        this.interfaceIsDebug = interfaceIsDebug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.Interface_debug_whether
     *
     * @return the value of test_interface.Interface_debug_whether
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getInterfaceDebugWhether() {
        return interfaceDebugWhether;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.Interface_debug_whether
     *
     * @param interfaceDebugWhether the value for test_interface.Interface_debug_whether
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceDebugWhether(Boolean interfaceDebugWhether) {
        this.interfaceDebugWhether = interfaceDebugWhether;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.getattr_p
     *
     * @return the value of test_interface.getattr_p
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getGetattrP() {
        return getattrP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.getattr_p
     *
     * @param getattrP the value for test_interface.getattr_p
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setGetattrP(String getattrP) {
        this.getattrP = getattrP == null ? null : getattrP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.pid
     *
     * @return the value of test_interface.pid
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.pid
     *
     * @param pid the value for test_interface.pid
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.save_result
     *
     * @return the value of test_interface.save_result
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getSaveResult() {
        return saveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.save_result
     *
     * @param saveResult the value for test_interface.save_result
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setSaveResult(Boolean saveResult) {
        this.saveResult = saveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.select_database
     *
     * @return the value of test_interface.select_database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getSelectDatabase() {
        return selectDatabase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.select_database
     *
     * @param selectDatabase the value for test_interface.select_database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setSelectDatabase(String selectDatabase) {
        this.selectDatabase = selectDatabase == null ? null : selectDatabase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.database_field
     *
     * @return the value of test_interface.database_field
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getDatabaseField() {
        return databaseField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.database_field
     *
     * @param databaseField the value for test_interface.database_field
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setDatabaseField(String databaseField) {
        this.databaseField = databaseField == null ? null : databaseField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.is_database
     *
     * @return the value of test_interface.is_database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Boolean getIsDatabase() {
        return isDatabase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.is_database
     *
     * @param isDatabase the value for test_interface.is_database
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setIsDatabase(Boolean isDatabase) {
        this.isDatabase = isDatabase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_interface.interface_type
     *
     * @return the value of test_interface.interface_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_interface.interface_type
     *
     * @param interfaceType the value for test_interface.interface_type
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType == null ? null : interfaceType.trim();
    }
}