package com.dieson.green.pojo;

public class Works {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.id
     *
     * @return the value of works.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.id
     *
     * @param id the value for works.id
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.name
     *
     * @return the value of works.name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.name
     *
     * @param name the value for works.name
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}