package com.dieson.green.dao;

import com.dieson.green.pojo.AlembicVersion;

public interface AlembicVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alembic_version
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int deleteByPrimaryKey(String versionNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alembic_version
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(AlembicVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alembic_version
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(AlembicVersion record);
}