package com.dieson.green.dao;

import com.dieson.green.pojo.Depend;

public interface DependMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depend
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(Depend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depend
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(Depend record);
}