package com.dieson.green.dao;

import com.dieson.green.pojo.EmialReports;

public interface EmialReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_reports
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_reports
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(EmialReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_reports
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(EmialReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_reports
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    EmialReports selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_reports
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKeySelective(EmialReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_reports
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKey(EmialReports record);
}