package com.dieson.green.dao;

import com.dieson.green.pojo.MockServer;

public interface MockServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_server
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_server
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(MockServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_server
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(MockServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_server
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    MockServer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_server
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKeySelective(MockServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_server
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKey(MockServer record);
}