package com.dieson.green.dao;

import com.dieson.green.pojo.Models;

public interface ModelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(Models record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(Models record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    Models selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKeySelective(Models record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKey(Models record);
    
    /**
     * 校验模块名称是否存在
     */
    Integer checkModelName(String model_name);
}