package com.dieson.green.dao;

import com.dieson.green.pojo.Registrations;

public interface RegistrationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registrations
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(Registrations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registrations
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(Registrations record);
}