package com.dieson.green.dao;

import com.dieson.green.pojo.Tasks;

public interface TasksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(Tasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(Tasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    Tasks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKeySelective(Tasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKey(Tasks record);
}