package com.dieson.green.dao;

import com.dieson.green.pojo.TestCaseResults;

public interface TestCaseResultsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_results
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_results
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int insert(TestCaseResults record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_results
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int insertSelective(TestCaseResults record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_results
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    TestCaseResults selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_results
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int updateByPrimaryKeySelective(TestCaseResults record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_results
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int updateByPrimaryKey(TestCaseResults record);
}