package com.dieson.green.dao;

import com.dieson.green.pojo.TestInterface;

public interface TestInterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_interface
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_interface
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(TestInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_interface
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(TestInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_interface
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    TestInterface selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_interface
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKeySelective(TestInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_interface
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKey(TestInterface record);
}