package com.dieson.green.dao;

import java.util.List;

import com.dieson.green.pojo.TestEnvironment;

public interface TestEnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insert(TestEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int insertSelective(TestEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    TestEnvironment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKeySelective(TestEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Mon Jul 09 15:06:28 CST 2018
     */
    int updateByPrimaryKey(TestEnvironment record);
    
    /**
     * 查询所有测试环境信息
     */
    List<TestEnvironment> selectTestEnvironment();
    
    /**
     * 校验测试环境是否存在
     */
    Integer checkTestEnvironment(String url);
}