package com.dieson.green.dao;

import com.dieson.green.pojo.TestCase;

public interface TestCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    int insert(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    int insertSelective(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    TestCase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    int updateByPrimaryKeySelective(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbg.generated Fri Nov 02 15:36:44 CST 2018
     */
    int updateByPrimaryKey(TestCase record);
}