package com.dieson.green.dao;


import com.dieson.green.pojo.TestEnvironment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TestEnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int insert(TestEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int insertSelective(TestEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    TestEnvironment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int updateByPrimaryKeySelective(TestEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_environment
     *
     * @mbg.generated Fri Nov 02 15:28:10 CST 2018
     */
    int updateByPrimaryKey(TestEnvironment record);

    /**
     * 获取测试环境列表
     */
    List<TestEnvironment> selectTestEnvironment() throws Exception;

    /**
     * 校验测试环境是否存在
     */
    int checkTestEnvironment(String url) throws Exception;

    /**
     * 获取测试环境的总数
     */
    int selectEnvironmentCount() throws Exception;

    /**
     * 根据名称获取测试环境url
     */
    String selectTestEnvironmentByName(@Param("name") String name) throws Exception;

    /**
     * 根据名称删除测试环境
     * @param name
     * @return
     */
    int deleteByName(@Param("name") String name);
}