package com.dieson.green.dao;

import org.apache.ibatis.annotations.Param;

import com.dieson.green.pojo.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Thu Jun 14 18:06:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Thu Jun 14 18:06:01 CST 2018
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Thu Jun 14 18:06:01 CST 2018
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Thu Jun 14 18:06:01 CST 2018
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Thu Jun 14 18:06:01 CST 2018
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbg.generated Thu Jun 14 18:06:01 CST 2018
	 */
	int updateByPrimaryKey(User record);

	int checkUserName(String username);

	User selectLogin(@Param("username") String username, @Param("password") String password);

	int updatePasswordByUsername(@Param("username") String username, @Param("passwordNew") String passwordNew);

	int checkPassword(@Param("password") String password, @Param("userId") Integer userId);
}